import Head from "next/head";
import MyHeader from "../components/header/header";
import MyPromo from "../components/promo/promo";
import MyCards from "../components/cards/cards";
import MyFooter from "../components/footer/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title className="text-3xl font-bold underline">
          KOJI - rooms for you
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MyHeader />
        <MyPromo />
        <MyFooter />
        <MyCards />
      </main>
    </div>
  );
}
